MiRedMetropolitana/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("aplicacion.urls", namespace="aplicacion")),
]

aplicacion/urls.py
from django.urls import path
from .views import *

app_name = "aplicacion"

urlpatterns = [
    path('', index, name="index"),
    path('bip', bip, name="bip"),
    path('metro', metro, name="metro"),
    path('micro', micro, name="micro"),
]

aplicacion/models.py
from django.db import models

# Create your models here.

aplicacion/views.py
from django.shortcuts import render
from .utils import *


# Create your views here.

def index(request):
    return render(
        request,
        "index.html",
        {
            "tarjeta": getTarjeta(),
            "lineas": getMetro(),
            "micros": getMicros(),
        }
    )

def bip(request):
    return render(
        request,
        "servicios/bip.html",
        {
            "tarjeta": getTarjeta()
        }
    )

def metro(request):
    return render(
        request,
        "servicios/metro.html",
        {
            "lineas": getMetro(),
        }
    )

def micro(request):
    return render(
        request,
        "servicios/micro.html",
        {
            "micros": getMicros(),
        }
    )

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mi Red Metropolitana</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/htmx.min.js' %}"></script>
  </head>
  <body>
    <section class="">{% block contenido %} {% endblock %}</section>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
{% include 'servicios/bip.html' %}
{% include 'servicios/metro.html' %}
{% include 'servicios/micro.html' %}
{% endblock %}

templates/servicios/bip.html
<div
  class="tarjeta"
  hx-get="{% url 'aplicacion:bip' %}"
  hx-trigger="every 10m"
  hx-swap="outerHTML"
>
  <h5>Tarjeta {{ tarjeta.tipo }} {{ tarjeta.numero }}</h5>
  <h1>$ {{ tarjeta.saldo }}</h1>
</div>

templates/servicios/metro.html
<div
  class="lineas"
  hx-get="{% url 'aplicacion:metro' %}"
  hx-trigger="every 2m"
  hx-swap="outerHTML"
>
  {% for linea in lineas %}
  <div>
    <h2 class="linea" style="--linea: {{ linea.color }};">
      {{ linea.nombre|upper }}
    </h2>
  </div>
  {% endfor %}
</div>

templates/servicios/micro.html
<div
  class="micros"
  hx-get="{% url 'aplicacion:micro' %}"
  hx-trigger="every 1m"
  hx-swap="outerHTML"
>
  {% for micro in micros.micros %}
  <div
    class="row micro"
    style="--micro: {% if forloop.counter0 == 0 %}#39974b{% elif forloop.counter0 == 1 %}#7F7F7F{% else %}#4C4C4C{% endif %};--opacity: {% if forloop.counter0 == 0 %}1{% elif forloop.last %}0.6{% else %}0.8{% endif %};"
  >
    <div class="col-md-4 servicio">{{ micro.servicio }}</div>
    <div class="col-md-4 patente">
      ({{ micro.patente }}) {{ micro.distancia }} mts
    </div>
    <div class="col-md-4 llegada">{{ micro.llegada }}</div>
  </div>
  {% endfor %}
  <span class="paradero">{{ micros.paradero }}</span>
</div>